apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: markmaksi/auth:latest # Docker image
          env:
            - name: MONGO_URL
              value: mongodb://auth-mongo-service:27017/auth
            - name: ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: auth-secret
                  key: ACCESS_TOKEN
            - name: ACCESS_TOKEN_EXPIRES_IN
              valueFrom:
                secretKeyRef:
                  name: auth-secret
                  key: ACCESS_TOKEN_EXPIRES_IN
            - name: EMAIL_PASS
              valueFrom:
                secretKeyRef:
                  name: auth-secret
                  key: EMAIL_PASS
            - name: EMAIL_USER
              valueFrom:
                secretKeyRef:
                  name: auth-secret
                  key: EMAIL_USER
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth
  ports:
    - name: auth
      protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP
