apiVersion: apps/v1
kind: Deployment
metadata:
  name: tickets-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tickets
  template:
    metadata:
      labels:
        app: tickets
    spec:
      containers:
        - name: tickets
          image: markmaksi/tickets:latest # Docker image
          env:
            - name: NATS_URL
              value: http://nats-service:4222
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: ACCESS_TOKEN
              value: fsnjd37KSr4und58isMnX
            - name: ACCESS_TOKEN_EXPIRES_IN
              value: 15m
            - name: MONGO_URL
              value: mongodb://tickets-mongo-service:27017/tickets
---
apiVersion: v1
kind: Service
metadata:
  name: tickets-service
spec:
  selector:
    app: tickets
  ports:
    - name: tickets
      protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP
